version: "3"

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - code:/var/www/html
            - ./site.conf:/etc/nginx/conf.d/default.conf
        links:
            - drupal
    drupal:
        image: drupal:7-fpm
        volumes:
            - code:/var/www/html
        restart: always
        links:
            - db
    db:
        image: mysql:5.5
        #command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: LMsb9170+

    adminer:
        image: adminer
        restart: always
        ports:
            - 8000:8080
        links:
            - db

volumes:
   code:

